# Generated by Django 6.0.7 on 2026-07-14 10:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("initial_address", models.CharField(max_length=255, unique=True)),
                ("found_name", models.CharField(blank=True, max_length=255, null=True)),
                ("blob", models.FileField(upload_to="ni_deeds/deeds/")),
                ("content", models.JSONField(blank=True, default=dict)),
                ("timestamp_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
