# Generated by Django 6.0.7 on 2026-08-20 19:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('initial_address', models.CharField(db_index=True, max_length=255, unique=True)),
                ('found_name', models.CharField(blank=True, max_length=255, unique=True)),
                ('timestamp_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('blob', models.FileField(upload_to='ni_deeds/deeds/')),
                ('content', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('processing_log', models.TextField(blank=True, default='')),
                ('deleted_on', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('timestamp_on', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='ni_deeds.owner')),
            ],
        ),
    ]
