# Generated by Django 6.0.7 on 2026-08-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ni_deeds", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="found_name",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="initial_address",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
