# Generated by Django 6.0.7 on 2026-07-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ni_deeds", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="deleted_on",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="property",
            name="initial_address",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="property",
            unique_together={("initial_address", "deleted_on")},
        ),
    ]
