# Generated by Django 6.0.7 on 2026-07-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ni_deeds', '0002_property_deleted_on_alter_property_initial_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
