# Generated by Django 6.0.7 on 2026-07-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ni_deeds', '0003_property_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='processing_log',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RemoveField(
            model_name='property',
            name='deleted_on',
        ),
        migrations.AddField(
            model_name='property',
            name='deleted_on',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
