# Generated by Django 6.0.7 on 2026-07-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ni_deeds', '0004_property_processing_log_alter_property_deleted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='processing_log',
            field=models.TextField(blank=True, default=''),
        ),
    ]
