# Generated by Django 6.0.7 on 2026-08-12 18:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ni_deeds', '0005_alter_property_processing_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('initial_address', models.CharField(max_length=255, unique=True)),
                ('found_name', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='ni_deeds.owner'),
        ),
    ]
