# Generated by Django 6.0.7 on 2026-08-12 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ni_deeds', '0007_custom'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='property',
                    unique_together={('owner', 'deleted_on')},
                ),
                migrations.RemoveField(
                    model_name='property',
                    name='found_name',
                ),
                migrations.RemoveField(
                    model_name='property',
                    name='initial_address',
                ),
            ],
            database_operations=[],
        ),
    ]
